// ─────────────────────────────────────────────────────────────
// Template Synthesizer — Response Assembly Engine
// ─────────────────────────────────────────────────────────────
// Port of backend/brain/template_synthesizer.py
// Assembles solver outputs and retrieved knowledge into coherent responses.
// No neural network — rule-based template composition.

use std::collections::HashMap;

/// All inputs to the synthesizer.
#[derive(Debug, Clone)]
pub struct SynthesisContext {
    pub prompt: String,
    pub intent: String,
    pub solver_answer: String,
    pub solver_confidence: f64,
    pub solver_name: String,
    pub retrieved_passages: Vec<String>,
    pub retrieved_scores: Vec<f64>,
    pub reasoning_trace: Vec<String>,
}

impl Default for SynthesisContext {
    fn default() -> Self {
        Self {
            prompt: String::new(),
            intent: "general".to_string(),
            solver_answer: String::new(),
            solver_confidence: 0.0,
            solver_name: String::new(),
            retrieved_passages: Vec::new(),
            retrieved_scores: Vec::new(),
            reasoning_trace: Vec::new(),
        }
    }
}

/// Assembles algorithmic solver outputs into coherent responses.
/// Strategy:
///   1. High-confidence solver answer → format and return
///   2. Solver + retrieval → combine enriched response
///   3. Retrieval-only → synthesize from passages
///   4. Solver-only with low confidence → return as-is
///   5. Structured fallback
pub struct TemplateSynthesizer {
    total_syntheses: u64,
}

impl TemplateSynthesizer {
    pub fn new() -> Self {
        Self { total_syntheses: 0 }
    }

    /// Synthesize a response from solver output and retrieved knowledge.
    pub fn synthesize(&mut self, ctx: &SynthesisContext) -> String {
        self.total_syntheses += 1;

        // Strategy 1: High-confidence solver answer
        if ctx.solver_confidence >= 0.70 && !ctx.solver_answer.is_empty() {
            return self.format_solver_response(&ctx.intent, &ctx.solver_answer);
        }

        // Strategy 2: Combine solver + retrieval
        if !ctx.solver_answer.is_empty() && !ctx.retrieved_passages.is_empty() {
            return self.combine_solver_and_retrieval(ctx);
        }

        // Strategy 3: Retrieval-only response
        if !ctx.retrieved_passages.is_empty() {
            return self.retrieval_response(ctx);
        }

        // Strategy 4: Solver-only with low confidence
        if !ctx.solver_answer.is_empty() {
            return ctx.solver_answer.clone();
        }

        // Strategy 5: Structured fallback
        self.structured_fallback(ctx)
    }

    fn format_solver_response(&self, intent: &str, answer: &str) -> String {
        let footer = match intent {
            "math" => {
                "*Computed by the Cognitive Core Engine (deterministic, zero-hallucination).*"
            }
            "code" => {
                "*Generated by the Cognitive Core Engine — pattern-matched and template-verified.*"
            }
            "logic" => {
                "*Derived using formal logic (forward/backward chaining). Provably correct.*"
            }
            "extraction" => return answer.to_string(),
            "plan" => "*Plan generated by task decomposition analysis.*",
            "verification" => return answer.to_string(),
            _ => "*Response assembled from knowledge retrieval (BM25) and algorithmic analysis.*",
        };
        format!("{}\n\n---\n{}", answer, footer)
    }

    fn combine_solver_and_retrieval(&self, ctx: &SynthesisContext) -> String {
        let mut sections = vec![ctx.solver_answer.clone()];

        let relevant = self.select_best_passages(&ctx.retrieved_passages, &ctx.retrieved_scores, 3);

        if !relevant.is_empty() {
            sections.push("\n### Additional Context\n".to_string());
            for (passage, _score) in &relevant {
                let cleaned = Self::clean_passage(passage);
                if !cleaned.is_empty() {
                    sections.push(format!("- {}", cleaned));
                }
            }
        }

        sections.join("\n")
    }

    fn retrieval_response(&self, ctx: &SynthesisContext) -> String {
        let relevant = self.select_best_passages(&ctx.retrieved_passages, &ctx.retrieved_scores, 5);

        if relevant.is_empty() {
            return self.structured_fallback(ctx);
        }

        let is_question = ctx.prompt.trim().ends_with('?')
            || [
                "what", "how", "why", "when", "where", "who", "which", "is ", "can ", "does ",
            ]
            .iter()
            .any(|q| ctx.prompt.to_lowercase().starts_with(q));

        let mut sections = Vec::new();
        if is_question {
            sections.push("Based on the available knowledge:\n".to_string());
        } else {
            sections.push("Here's what I found:\n".to_string());
        }

        for (passage, _score) in &relevant {
            let cleaned = Self::clean_passage(passage);
            if !cleaned.is_empty() {
                if cleaned.len() > 200 {
                    sections.push(format!("{}\n", cleaned));
                } else {
                    sections.push(format!("• {}", cleaned));
                }
            }
        }

        sections.push(format!(
            "\n---\n*Retrieved from local knowledge base (BM25 scoring, {} relevant passages found).*",
            relevant.len()
        ));

        sections.join("\n")
    }

    fn structured_fallback(&self, ctx: &SynthesisContext) -> String {
        let prompt_summary: String = ctx.prompt.chars().take(200).collect();

        match ctx.intent.as_str() {
            "code" => format!(
                "I understand you're asking about code: \"{}\"\n\n\
                 While I don't have a pre-built template for this pattern:\n\n\
                 1. **Identify the core algorithm** — what data structure fits?\n\
                 2. **Define the interface** — what inputs/outputs?\n\
                 3. **Implement iteratively** — start simple, then optimize\n\
                 4. **Test with edge cases**\n\n\
                 Try rephrasing with a specific algorithm name.",
                prompt_summary
            ),
            "math" => format!(
                "I received your math question: \"{}\"\n\n\
                 I can solve:\n\
                 - Arithmetic expressions (e.g., '15 * 23 + 7')\n\
                 - Statistics (mean, median, std)\n\
                 - Linear equations (e.g., '3x + 5 = 20')\n\
                 - Number theory (primes, factorial, fibonacci)\n\n\
                 Try rephrasing with a clear mathematical expression.",
                prompt_summary
            ),
            _ => format!(
                "I processed your request: \"{}\"\n\n\
                 The Cognitive Core Engine analyzed this using:\n\
                 - Knowledge retrieval (BM25 search)\n\
                 - Algorithmic solvers (math, code, logic)\n\
                 - Pattern matching and template synthesis\n\n\
                 For more precise results, try:\n\
                 - A specific mathematical question\n\
                 - Requesting a specific algorithm\n\
                 - Asking about a known concept or pattern",
                prompt_summary
            ),
        }
    }

    fn select_best_passages(
        &self,
        passages: &[String],
        scores: &[f64],
        max_passages: usize,
    ) -> Vec<(String, f64)> {
        let paired: Vec<(&String, f64)> = passages.iter().zip(scores.iter().copied()).collect();

        let threshold = paired.iter().map(|(_, s)| *s).fold(0.0f64, f64::max) * 0.3;

        let mut filtered: Vec<(String, f64)> = paired
            .iter()
            .filter(|(p, s)| *s >= threshold && p.trim().len() > 20)
            .map(|(p, s)| ((*p).clone(), *s))
            .collect();

        filtered.truncate(max_passages);
        filtered
    }

    fn clean_passage(passage: &str) -> String {
        let cleaned = passage.trim().to_string();
        // Remove excessive whitespace
        let re = regex::Regex::new(r"\n{3,}").unwrap();
        let cleaned = re.replace_all(&cleaned, "\n\n").to_string();

        if cleaned.len() > 500 {
            // Try to cut at a sentence boundary
            if let Some(cut_point) = cleaned[..500].rfind('.') {
                if cut_point > 200 {
                    return cleaned[..=cut_point].to_string();
                }
            }
            return format!("{}...", &cleaned[..500]);
        }
        cleaned
    }

    pub fn get_stats(&self) -> HashMap<String, u64> {
        let mut stats = HashMap::new();
        stats.insert("total_syntheses".into(), self.total_syntheses);
        stats
    }
}

impl Default for TemplateSynthesizer {
    fn default() -> Self {
        Self::new()
    }
}
